<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmpresasSeeder extends Seeder
{
    public function run()
    {
        DB::table('empresas')->insert([
            [
        'razon_social' => 'Tech Solutions S.A.',
        'municipio' => 'Monterrey',
        'departamento' => 'Nuevo León',
        'fecha_matricula' => '2022-05-10',
        'direccion' => 'Av. Revolución 123',
        'rep_legal' => 'Carlos Pérez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Agroindustria del Norte',
        'municipio' => 'Guadalajara',
        'departamento' => 'Jalisco',
        'fecha_matricula' => '2021-11-20',
        'direccion' => 'Calle Hidalgo 45',
        'rep_legal' => 'María López',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Servicios Financieros del Bajío',
        'municipio' => 'León',
        'departamento' => 'Guanajuato',
        'fecha_matricula' => '2023-03-15',
        'direccion' => 'Blvd. Campestre 78',
        'rep_legal' => 'Juan Hernández',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Construcciones del Centro S.A.',
        'municipio' => 'Querétaro',
        'departamento' => 'Querétaro',
        'fecha_matricula' => '2020-09-18',
        'direccion' => 'Av. Corregidora 220',
        'rep_legal' => 'Laura Sánchez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Distribuidora del Pacífico',
        'municipio' => 'Mazatlán',
        'departamento' => 'Sinaloa',
        'fecha_matricula' => '2019-07-01',
        'direccion' => 'Calle del Mar 56',
        'rep_legal' => 'Pedro Ramírez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Inversiones Rivera S. de R.L.',
        'municipio' => 'Torreón',
        'departamento' => 'Coahuila',
        'fecha_matricula' => '2023-01-05',
        'direccion' => 'Av. Morelos 89',
        'rep_legal' => 'Gabriela Torres',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Comercializadora del Sureste',
        'municipio' => 'Mérida',
        'departamento' => 'Yucatán',
        'fecha_matricula' => '2021-02-17',
        'direccion' => 'Calle 60 #456',
        'rep_legal' => 'Ricardo Gómez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Transportes del Bajío',
        'municipio' => 'Celaya',
        'departamento' => 'Guanajuato',
        'fecha_matricula' => '2020-12-09',
        'direccion' => 'Carretera Panamericana km 3',
        'rep_legal' => 'Miguel Rojas',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Energías Limpias del Norte',
        'municipio' => 'Saltillo',
        'departamento' => 'Coahuila',
        'fecha_matricula' => '2024-04-11',
        'direccion' => 'Blvd. Venustiano Carranza 340',
        'rep_legal' => 'Diana Flores',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Consultores del Valle S.C.',
        'municipio' => 'Toluca',
        'departamento' => 'Estado de México',
        'fecha_matricula' => '2023-09-21',
        'direccion' => 'Av. Hidalgo 780',
        'rep_legal' => 'Jorge Castillo',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Café del Bosque',
        'municipio' => 'Xalapa',
        'departamento' => 'Veracruz',
        'fecha_matricula' => '2018-06-10',
        'direccion' => 'Calle Magnolia 12',
        'rep_legal' => 'Beatriz Mendoza',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Maderas del Sur',
        'municipio' => 'Tuxtla Gutiérrez',
        'departamento' => 'Chiapas',
        'fecha_matricula' => '2020-03-25',
        'direccion' => 'Carretera Sur 54',
        'rep_legal' => 'Luis Villalobos',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Industrias del Golfo',
        'municipio' => 'Tampico',
        'departamento' => 'Tamaulipas',
        'fecha_matricula' => '2022-08-14',
        'direccion' => 'Av. Hidalgo 345',
        'rep_legal' => 'Sandra Aguilar',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Artesanías del Desierto',
        'municipio' => 'Hermosillo',
        'departamento' => 'Sonora',
        'fecha_matricula' => '2019-10-05',
        'direccion' => 'Calle Sonora 99',
        'rep_legal' => 'Mario Castro',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Alimentos del Campo',
        'municipio' => 'Culiacán',
        'departamento' => 'Sinaloa',
        'fecha_matricula' => '2023-12-20',
        'direccion' => 'Calle Morelos 155',
        'rep_legal' => 'Nora Pérez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Textiles del Bajío',
        'municipio' => 'Irapuato',
        'departamento' => 'Guanajuato',
        'fecha_matricula' => '2021-05-08',
        'direccion' => 'Av. Guerrero 98',
        'rep_legal' => 'Rafael Díaz',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Ferretería Central',
        'municipio' => 'Puebla',
        'departamento' => 'Puebla',
        'fecha_matricula' => '2020-11-11',
        'direccion' => 'Calle Reforma 33',
        'rep_legal' => 'Claudia Reyes',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Panadería San Juan',
        'municipio' => 'Querétaro',
        'departamento' => 'Querétaro',
        'fecha_matricula' => '2019-01-22',
        'direccion' => 'Calle Madero 234',
        'rep_legal' => 'José Morales',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Innovaciones Digitales',
        'municipio' => 'Ciudad de México',
        'departamento' => 'CDMX',
        'fecha_matricula' => '2024-02-28',
        'direccion' => 'Av. Reforma 1000',
        'rep_legal' => 'Daniela Navarro',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Clínica Vida Salud',
        'municipio' => 'Chihuahua',
        'departamento' => 'Chihuahua',
        'fecha_matricula' => '2023-06-13',
        'direccion' => 'Calle Juárez 45',
        'rep_legal' => 'Fernando Vázquez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Estudios Fotográficos Luna',
        'municipio' => 'Oaxaca de Juárez',
        'departamento' => 'Oaxaca',
        'fecha_matricula' => '2021-03-09',
        'direccion' => 'Calle Alcalá 14',
        'rep_legal' => 'Lucía Luna',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Editorial del Norte',
        'municipio' => 'Monterrey',
        'departamento' => 'Nuevo León',
        'fecha_matricula' => '2022-07-25',
        'direccion' => 'Av. Constitución 456',
        'rep_legal' => 'Héctor Robles',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Logística Integral S.A.',
        'municipio' => 'San Luis Potosí',
        'departamento' => 'San Luis Potosí',
        'fecha_matricula' => '2020-04-18',
        'direccion' => 'Blvd. Salvador Nava 102',
        'rep_legal' => 'Verónica Estrada',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Hotel Playa Bonita',
        'municipio' => 'Cancún',
        'departamento' => 'Quintana Roo',
        'fecha_matricula' => '2018-08-30',
        'direccion' => 'Av. Kukulcán km 10',
        'rep_legal' => 'Andrés Torres',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Academia del Saber',
        'municipio' => 'Tepic',
        'departamento' => 'Nayarit',
        'fecha_matricula' => '2022-01-05',
        'direccion' => 'Calle Juárez 200',
        'rep_legal' => 'Rosa Martínez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Inmobiliaria Los Pinos',
        'municipio' => 'Durango',
        'departamento' => 'Durango',
        'fecha_matricula' => '2021-10-14',
        'direccion' => 'Calle 5 de Febrero 76',
        'rep_legal' => 'Víctor Cruz',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Farmacia del Pueblo',
        'municipio' => 'Cuernavaca',
        'departamento' => 'Morelos',
        'fecha_matricula' => '2019-12-03',
        'direccion' => 'Calle Matamoros 22',
        'rep_legal' => 'Martha Roldán',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Consultoría Jurídica Global',
        'municipio' => 'Zacatecas',
        'departamento' => 'Zacatecas',
        'fecha_matricula' => '2024-05-02',
        'direccion' => 'Av. Hidalgo 210',
        'rep_legal' => 'Roberto Cárdenas',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Vidriería Moderna',
        'municipio' => 'Mexicali',
        'departamento' => 'Baja California',
        'fecha_matricula' => '2023-10-07',
        'direccion' => 'Blvd. Benito Juárez 98',
        'rep_legal' => 'Leticia Soto',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Pinturas del Sol',
        'municipio' => 'Tijuana',
        'departamento' => 'Baja California',
        'fecha_matricula' => '2022-02-12',
        'direccion' => 'Av. Insurgentes 456',
        'rep_legal' => 'Óscar Beltrán',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Heladería La Estrella',
        'municipio' => 'Colima',
        'departamento' => 'Colima',
        'fecha_matricula' => '2021-09-01',
        'direccion' => 'Calle Hidalgo 34',
        'rep_legal' => 'Cecilia Núñez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Taller Mecánico Rodríguez',
        'municipio' => 'Aguascalientes',
        'departamento' => 'Aguascalientes',
        'fecha_matricula' => '2020-05-28',
        'direccion' => 'Calle Morelos 78',
        'rep_legal' => 'Carlos Rodríguez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Consultores Ambientales Verdes',
        'municipio' => 'Villahermosa',
        'departamento' => 'Tabasco',
        'fecha_matricula' => '2023-11-04',
        'direccion' => 'Av. Universidad 50',
        'rep_legal' => 'Sara Jiménez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Cinemas del Norte',
        'municipio' => 'Monterrey',
        'departamento' => 'Nuevo León',
        'fecha_matricula' => '2020-10-16',
        'direccion' => 'Av. Garza Sada 321',
        'rep_legal' => 'Julián Torres',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Diseños Creativos Luna',
        'municipio' => 'San Cristóbal de las Casas',
        'departamento' => 'Chiapas',
        'fecha_matricula' => '2021-06-09',
        'direccion' => 'Calle Real de Guadalupe 15',
        'rep_legal' => 'Elena Flores',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Refacciones Express',
        'municipio' => 'Morelia',
        'departamento' => 'Michoacán',
        'fecha_matricula' => '2024-01-22',
        'direccion' => 'Av. Madero 140',
        'rep_legal' => 'Francisco Ortega',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Florería Primavera',
        'municipio' => 'Veracruz',
        'departamento' => 'Veracruz',
        'fecha_matricula' => '2022-03-30',
        'direccion' => 'Calle Juárez 101',
        'rep_legal' => 'Patricia Domínguez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Panificadora La Espiga',
        'municipio' => 'Pachuca',
        'departamento' => 'Hidalgo',
        'fecha_matricula' => '2023-08-18',
        'direccion' => 'Av. Revolución 78',
        'rep_legal' => 'Julio Herrera',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Centro Médico Los Ángeles',
        'municipio' => 'La Paz',
        'departamento' => 'Baja California Sur',
        'fecha_matricula' => '2020-02-27',
        'direccion' => 'Calle Constitución 123',
        'rep_legal' => 'Isabel Ramírez',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'razon_social' => 'Hotel Sierra Dorada',
        'municipio' => 'Zihuatanejo',
        'departamento' => 'Guerrero',
        'fecha_matricula' => '2021-12-14',
        'direccion' => 'Playa La Ropa s/n',
        'rep_legal' => 'Hugo Pineda',
        'created_at' => now(),
        'updated_at' => now(),
    ],
        ]);
    }
}
